database:
  type: sqlite          # sqlite | mysql | postgres
  sqlite:
    file: plugins/SogurEco/economy.db
  mysql:
    host: localhost
    port: 3306
    database: sogureco
    username: root
    password: secret
    useSSL: false
  postgres:
    host: localhost
    port: 5432
    database: sogureco
    username: postgres
    password: secret

# other plugin config...
currency:
  symbol: "$"
  decimals: 2
