database:
  type: "sqlite" # Options: sqlite, mysql, mariadb, postgresql

  # Only used for MySQL/MariaDB/PostgreSQL
  host: "localhost"
  port: 3306
  name: "sogureco"
  user: "root"
  password: "password"

# other plugin config...
currency:
  currencyName: SogurCoin
  currencyNamePlural: SogurCoins
  decimals: 2
